name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1=py37_0
  - adal=1.2.2=py_0
  - affine=2.3.0=py_0
  - aiohttp=3.6.1=py37h516909a_0
  - alembic=1.2.1=py_0
  - altair=3.2.0=py37_0
  - antlr-python-runtime=4.7.2=py37_1000
  - appdirs=1.4.3=py_1
  - asciitree=0.3.3=py_2
  - asn1crypto=1.0.1=py37_0
  - astor=0.7.1=py_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrdict=2.0.1=py_0
  - attrs=19.2.0=py_0
  - backcall=0.1.0=py_0
  - backports=1.0=py_2
  - basemap=1.2.1=py37hd759880_1
  - beautifulsoup4=4.8.0=py37_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - blosc=1.17.0=he1b5a44_1
  - bokeh=1.3.4=py37_0
  - boost-cpp=1.70.0=h8e57a91_2
  - boto3=1.9.244=py_0
  - botocore=1.12.245=py_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.9.11=hecc5488_0
  - cached-property=1.5.1=py_0
  - cachetools=2.1.0=py_0
  - cairo=1.16.0=hfb77d84_1002
  - cartopy=0.17.0=py37hd759880_1006
  - cc-plugin-ncei=2.0.2=py_3
  - certifi=2019.9.11=py37_0
  - certipy=0.1.3=py_0
  - cf-units=2.1.3=py37hc1659b7_0
  - cffi=1.12.3=py37h8022711_0
  - cfitsio=3.470=hb60a0a2_2
  - cftime=1.0.3.4=py37hd352d35_1001
  - chardet=3.0.4=py37_1003
  - ciso=0.1.0=py37h3010b51_0
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - climlab=0.7.5=py37h7eb8c7e_1
  - cloudpickle=1.2.2=py_0
  - cmocean=2.0=py_1
  - colorcet=2.0.1=py_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - compliance-checker=4.2.2=py37_0
  - configobj=5.0.6=py_0
  - configparser=3.7.3=py37_1
  - configurable-http-proxy=1.3.0=0
  - croniter=0.3.30=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - ctd=1.0.0=py_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - cytoolz=0.10.0=py37h516909a_0
  - dask=2.2.0=py_0
  - dask-core=2.2.0=py_0
  - dask-gateway=0.2.0=py37_0
  - dask-glm=0.2.0=py_1
  - dask-kubernetes=0.9.2=py_0
  - dask-ml=1.0.0=py_0
  - datashader=0.7.0=py_1
  - datashape=0.5.4=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_3
  - distributed=2.2.0=py_1
  - docker-py=4.1.0=py37_0
  - docker-pycreds=0.4.0=py_0
  - docopt=0.6.2=py_1
  - docrep=0.2.7=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - eofs=1.4.0=py_0
  - erddapy=0.5.0=py_0
  - esmf=7.1.0=hcda5390_1008
  - esmpy=7.1.0=py37h24bf2e0_3
  - expat=2.2.5=he1b5a44_1003
  - fastcache=1.1.0=py37h516909a_0
  - fasteners=0.14.1=py_3
  - fiona=1.8.6=py37hf242f0b_3
  - folium=0.10.0=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - fribidi=1.0.5=h516909a_1002
  - fsspec=0.5.2=py_0
  - future=0.17.1=py37_1000
  - gast=0.3.2=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gcsfs=0.3.0=py_0
  - gdal=2.4.1=py37h5f563d9_8
  - geolinks=0.2.0=py_1
  - geopandas=0.5.1=py_0
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.4.3=hb6868eb_1001
  - geoviews=1.6.3=py_0
  - geoviews-core=1.6.3=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gmpy2=2.1.0b1=py37h04dde30_0
  - google-auth=1.6.3=py_0
  - google-auth-oauthlib=0.4.1=py_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h5933667_1
  - gridgeo=1.5.2=py_0
  - grpcio=1.23.0=py37he9ae1f9_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gsw=3.3.1=py37h516909a_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5netcdf=0.7.4=py_0
  - h5py=2.9.0=nompi_py37h513d04c_1104
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - heapdict=1.0.1=py_0
  - holoviews=1.12.5=py_0
  - hvplot=0.4.0=py_1
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imageio=2.6.1=py37_0
  - intake=0.5.3=py_0
  - intake-esm=2019.8.23=py_0
  - intake-xarray=0.3.1=py_0
  - ioos-tools=1.3.3=py_0
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipyleaflet=0.11.1=py37_1
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - iris=2.2.0=py37_1003
  - isodate=0.6.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py_2
  - jupyter-server-proxy=1.1.0=py_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.5.0=py_0
  - jupyterhub=1.0.0=py37_0
  - jupyterlab=1.0.9=py37_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.10=h58c409b_1005
  - keras=2.2.5=py37_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=13_openblas
  - libcblas=3.8.0=13_openblas
  - libclang=9.0.0=hc9558a2_1
  - libcurl=7.65.3=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.4.1=heae24aa_8
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=13_openblas
  - libllvm9=9.0.0=hc9558a2_2
  - libnetcdf=4.6.2=h303dfb8_1003
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_1
  - libprotobuf=3.8.0=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.0=he1b5a44_1
  - libspatialite=4.3.0a=h79dc798_1030
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.32.0=h516909a_0
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.8.4=h516909a_0
  - libxml2=2.9.9=hee79883_5
  - libxslt=1.1.33=h31b3aaa_0
  - llvmlite=0.29.0=py37hfd453ef_1
  - locket=0.2.0=py_2
  - lxml=4.4.1=py37h7ec2d77_0
  - lz4=2.1.9=py37hd79334b_0
  - lz4-c=1.8.3=he1b5a44_1001
  - mako=1.1.0=py_0
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - marshmallow=3.0.5=py_0
  - marshmallow-oneofschema=2.0.1=py_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mechanicalsoup=0.12.0=py_0
  - mercantile=1.1.2=py_0
  - metpy=0.10.2=py37_0
  - mistune=0.8.4=py37h14c3975_1000
  - mock=3.0.5=py37_0
  - monotonic=1.5=py_0
  - mpc=1.1.0=hb20f59a_1006
  - mpfr=4.0.2=he80fd80_0
  - mpi=1.0=mpich
  - mpich=3.3.1=hc856adb_1
  - mpmath=1.1.0=py_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.6.2=py37hc9558a2_0
  - multidict=4.5.2=py37h14c3975_1000
  - multipledispatch=0.6.0=py_0
  - munch=2.3.2=py_0
  - mypy_extensions=0.4.2=py37_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - nbgitpuller=0.7.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf-fortran=4.4.5=h0789656_1004
  - netcdf4=1.5.1.2=py37h73a1b54_1
  - networkx=2.3=py_0
  - ninja=1.9.0=h6bb024c_0
  - nodejs=12.11.1=h10a4023_0
  - notebook=6.0.1=py37_0
  - nspr=4.20=hf484d3e_1000
  - nss=3.46=he751ad9_0
  - numba=0.45.1=py37hb3f55d8_0
  - numcodecs=0.6.3=py37hf484d3e_0
  - numpy=1.17.0=py37h95a1406_0
  - oauthlib=3.0.1=py_0
  - oceans=0.7.0=py_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h21c5421_1
  - openssl=1.1.1c=h516909a_0
  - owslib=0.18.0=py_0
  - packaging=19.2=py_0
  - paegan=1.1.4=py_1
  - palettable=3.3.0=py_0
  - pamela=1.0.0=py_0
  - pandas=0.24.2=py37hb3f55d8_0
  - pandas-flavor=0.1.2=py_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - panel=0.6.2=0
  - pango=1.42.4=ha030887_1
  - param=1.9.2=py_0
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - pathlib2=2.3.5=py37_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pendulum=2.0.5=py37_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.2.0=py37h6b7be26_0
  - pint=0.9=py37_2
  - pip=19.2.3=py37_0
  - pixman=0.38.0=h516909a_1003
  - pocean-core=1.9.0=py_0
  - podaacpy=2.4.0=py_0
  - pooch=0.5.2=py37_0
  - poppler=0.67.0=ha967d66_7
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_1
  - prefect=0.6.6=py_0
  - proj4=5.2.0=he1b5a44_1006
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.8.0=py37he1b5a44_1
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.6=py_0
  - pyasn1-modules=0.2.6=py_0
  - pycparser=2.19=py37_1
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pycurl=7.43.0.2=py37h16ce93b_1
  - pydap=3.2.2=py37_1000
  - pyepsg=0.4.0=py_0
  - pygc=1.2.1=py_1
  - pygeoif=0.7=py_1
  - pygments=2.4.2=py_0
  - pygpu=0.7.6=py37h3010b51_1000
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py37h3010b51_1002
  - pyke=1.1.1=py37_1000
  - pyoos=0.8.4=py_1
  - pyopenssl=19.0.0=py37_0
  - pyorbital=1.5.0=py_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.6=py37h516909a_1002
  - pyqt=5.12.3=py37hcca6a23_0
  - pyresample=1.13.1=py37hb3f55d8_0
  - pyrsistent=0.15.4=py37h516909a_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - pyspectral=0.9.2=py_0
  - pyspharm=1.0.9=py37h7eb8c7e_1004
  - python=3.7.3=h33d41f4_1
  - python-blosc=1.8.1=py37hf484d3e_0
  - python-box=3.4.5=py_0
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - python-geotiepoints=1.1.8=py37hd352d35_0
  - python-kubernetes=10.0.1=py37_0
  - python-slugify=3.0.3=py_0
  - python-snappy=0.5.4=py37hee44bf9_0
  - python-wget=3.2=py_0
  - pytorch-cpu=1.1.0=py37he1b5a44_0
  - pytz=2019.3=py_0
  - pytzdata=2019.3=py_0
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.0.3=py37hd352d35_1
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37h1768529_0
  - qt=5.12.5=h0c104cb_0
  - qtconsole=4.5.5=py_0
  - rasterio=1.0.25=py37hdff7cfa_0
  - readline=8.0=hf8c457e_0
  - regex=2019.08.19=py37h516909a_0
  - regionmask=0.4.0=py_0
  - requests=2.22.0=py37_1
  - requests-oauthlib=1.2.0=py_0
  - retrying=1.3.3=py_2
  - rio-cogeo=1.1.0=py_0
  - rsa=3.4.2=py_1
  - rtree=0.8.3=py37h666c49c_1002
  - ruamel.yaml=0.16.5=py37h516909a_1
  - ruamel.yaml.clib=0.2.0=py37h516909a_0
  - s3fs=0.3.3=py_0
  - s3transfer=0.2.1=py37_0
  - satpy=0.16.1=pyh326bf55_0
  - scikit-image=0.15.0=py37hb3f55d8_2
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py_1
  - seawater=3.3.4=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - shapely=1.6.4=py37hec07ddf_1006
  - simpervisor=0.3=py_1
  - simplejson=3.16.0=py37h14c3975_1002
  - six=1.12.0=py37_1000
  - snappy=1.1.7=he1b5a44_1002
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.1.0=py_0
  - soupsieve=1.9.4=py37_0
  - sqlalchemy=1.3.9=py37h516909a_0
  - sqlite=3.30.0=hcee41ef_0
  - statsmodels=0.10.1=py37hc1659b7_0
  - supermercado=0.0.5=py_0
  - sympy=1.4=py37_0
  - tabulate=0.8.5=py_0
  - tbb=2018.0.5=h2d50403_0
  - tblib=1.4.0=py_0
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1=h5ece82f_4
  - tensorflow-base=1.13.1=py37h5ece82f_4
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - text-unidecode=1.2=py_0
  - theano=1.0.4=py37hf484d3e_1000
  - tiledb=1.6.2=h69c774e_1
  - tiledb-py=0.4.3=py37hb78b526_1
  - timeout-decorator=0.4.1=py_0
  - tk=8.6.9=hed695b0_1003
  - toml=0.10.0=py_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - traittypes=0.2.1=py_1
  - trollimage=1.10.1=py_0
  - trollsift=0.3.2=py_0
  - typing=3.6.4=py37_0
  - typing_extensions=3.7.4=py37_0
  - tzcode=2019a=h516909a_1002
  - udunits2=2.2.27.6=h4e0c4b3_1001
  - unidecode=1.1.1=py_0
  - unyt=2.3.1=py_0
  - urllib3=1.25.6=py37_0
  - utide=0.2.4=py_0
  - vega=2.6.0=py37_0
  - vega_datasets=0.7.0=py_0
  - vincent=0.4.4=py_1
  - viscm=0.7=pyh24bf2e0_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - webob=1.8.5=py_0
  - websocket-client=0.56.0=py37_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - windspharm=1.7.0=py37_1001
  - xarray=0.12.3=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xesmf=0.2.0=py37_0
  - xgcm=0.2.0=py_0
  - xhistogram=0.1.1=py_0
  - xlrd=1.2.0=py_0
  - xmitgcm=0.4.1=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h516909a_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xrft=0.2.0=py_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py37h14c3975_1000
  - zarr=2.3.2=py37_0
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - atomicwrites==1.3.0
    - dask-labextension==1.0.0
    - importlib-metadata==0.23
    - more-itertools==7.2.0
    - pluggy==0.13.0
    - py==1.8.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytest==5.2.2
    - python-graphviz==0.13
    - zipp==0.6.0
prefix: /srv/conda/envs/notebook

