title: Earth and Environmental Data Science
author: Ryan Abernathey
copyright: 2016-2021
logo: eeds-logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
only_build_toc_files: true

execute:
  execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/earth-env-data-science/earth-env-data-science-book
  path_to_book: src
  branch: master

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "" # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: "https://pangeo.2i2c.cloud"

# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://earth-env-data-science.github.io"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
